version: '3'
services:
  app:
    image: longfinger-project/web
    restart: always
    build: 
      context: ./public/
      dockerfile: Dockerfile
    depends_on:
      - node
    ports: 
      - "3000:3000"
  node:
    restart: always
    image: longfinger-project/node
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
      - "27017:27017"

